/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: bbb72a6010dcdcca2f5cc7bbc73073bd)
interface __BaseEnv_Env {
	AUDIO: R2Bucket;
	OBJECT_PREFIX: "podcast";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "OBJECT_PREFIX">> {}
}
